/**
 **************************************************************
 * The Fans Together Website - v1.0.0
 **************************************************************
 * 
 * Product Page: 
 * Copyright 2022 @TFTTeam (https://www.tft-dev-team.com)
 * 
 * Coded by DavidSparker
 * 
 **************************************************************
 */

// import { NavigateNext } from "@mui/icons-material";
import React from "react";
import { News, NewsLinkItem } from "../components";

const news = [
  {
    title: "WHAT IS DISCORD",
    text: <>Discord <NewsLinkItem link="http://discord.com" text="(discord.com)" /> is an online communication service which allows users to interact through text, voice and video. It allows people to form their own spaces and communities to hang out with existing friends and to meet new people with similar interests. Each individual Discord server can have multiple channels to focus specific conversation topics in certain areas or just to help users find information quicker and easier. The use and progression of Discord is best explained by the creators of discord themselves.</>,
    picture: require("assets/images/news/discord/Discord Story 1.png"),
  },
  {
    picture: require("assets/images/news/discord/Discord Story 2.png"),
  },
  {
    title: "HOW DO THE FANS TOGETHER USE DISCORD?",
    text: <>At The Fans Together we have our own Discord server which we use as a place for all community members to interact with each other as they wish, whether it’s discussing the latest TFT news or getting to know other members. Our Discord server is used to relay information from our Twitter announcements but is also used for exclusive updates and potential upcoming news. Members are able to discuss and influence TFT decisions and it is the best place for feedback to be seen and acted upon. <br/><br/>
      If you already have a Discord account then you can join the TFT server here: <NewsLinkItem link="https://discord.gg/jHFCY2aGsv" text="https://discord.gg/jHFCY2aGsv"/><br/><br/>
      If you don’t have a Discord account yet then we will guide you through the process of creating an account and joining the TFT server so that you can participate in more community interactions.</>,
  },
  {
    title: "CREATING A DISCORD ACCOUNT",
    text: <>Discord can be used as a desktop or mobile app, as well as a traditional browser version. The account creation process is very similar on each version but to save you from downloading any files right now, we will be demonstrating the use of the browser version. This can be found at <NewsLinkItem link="http://discord.com" text="discord.com."/></>,
    picture: require("assets/images/news/discord/Discord.com.png"),
  },
  {
    text: "Click ‘Login’ and you will be taken to this page.",
    picture: require("assets/images/news/discord/Discord Login.png"),
  },
  {
    text: "Click ‘Register’ to begin your account creation process. You will then need to enter your email address, desired username, password and date of birth before agreeing to the terms and conditions. Once these have all been filled out click ‘Continue’.",
    picture: require("assets/images/news/discord/Discord Register.png")
  },
  {
    text: "Complete the captcha successfully and Discord will open on this window.",
    picture: require("assets/images/news/discord/Discord Intro.png"),
  },
  {
    title: "JOINING THE TFT SERVER",
    text: <>From the window which opened upon registration, click ‘Have an invite already? Join a server’ and you will be requested to enter the server invite link. These are generated by members of the Discord server and the TFT invite link is: <NewsLinkItem link="https://discord.gg/jHFCY2aGsv" text="https://discord.gg/jHFCY2aGsv"/></>,
    picture: require("assets/images/news/discord/Discord Invite Link.png"),
  },
  {
    text: "Congratulations, you’ve entered the TFT discord server! You will be greeted with server rules. However, before you can view other channels and participate in the community there are verification processes which must be completed. The first of these can be found by clicking on the message you received from Captcha.bot in the top left corner.",
    picture: require("assets/images/news/discord/Discord TFT Intro.png"),
  },
  {
    text: "Enter the given captcha in response to Captcha.bot. Take note that the captcha is case sensitive and doesn’t include spaces. An audio option is offered if preferred.",
    picture: require("assets/images/news/discord/Discord TFT Captcha.png"),
  },
  {
    text: "Once your captcha has been entered successfully you will have access to the full TFT server. Click the TFT icon in the top left to return there, this is how you navigate between servers. Once you’re in the server head to the ‘general’ channel and introduce yourself, there will be plenty of people there to interact with. (Make sure that you have verified your email address as some Discord servers will require this verification level for you to send messages.)",
    picture: require("assets/images/news/discord/Discord TFT General.png"),
  },
  {
    text: <>The list on the left are channels within the TFT server, feel free to explore and participate in as many as you like. You’ll find a variety of different conversation topics and Discord thrives on forming small communities within servers where you can interact with people particularly interested in the same channel topics. By clicking the gear icon in the bottom left you will be able to customise your profile and notification settings among other things but we will leave that with you to explore.<br/><br/>We hope you enjoy participating in our Discord server and interacting in our community as a TFT member!</>
  }
];

export default function NewsDiscord() {
  return (
    <News 
      mainImg={require("assets/images/news/discord/background.png")}
      title="How to get Involved - Discord"
      news={news}
    />
  )
}
